export const DEPARTAMENTOS = [
    {
      nombre: "Alta Verapaz",
      municipios: [
        "Cobán",
        "Chisec",
        "San Pedro Carchá",
        "Tactic",
        "Tamahú",
        "Tucurú",
        "Santa María Cahabón",
        "San Juan Chamelco",
        "Santa Cruz Verapaz",
        "San Cristóbal Verapaz",
        "Fray Bartolomé de las Casas",
        "Santa Catalina La Tinta",
        "Raxruhá",
      ],
    },
    {
      nombre: "Baja Verapaz",
      municipios: [
        "Salamá",
        "Cubulco",
        "Rabinal",
        "San Jerónimo",
        "Purulhá",
        "Granados",
      ],
    },
    {
      nombre: "Chimaltenango",
      municipios: [
        "Chimaltenango",
        "San José Poaquil",
        "San Martín Jilotepeque",
        "Comalapa",
        "Santa Apolonia",
        "Tecpán",
        "Patzún",
        "Pochuta",
        "Patzicía",
        "Acatenango",
        "Yepocapa",
        "San Andrés Itzapa",
        "Parramos",
        "Zaragoza",
        "El Tejar",
      ],
    },
    {
      nombre: "Chiquimula",
      municipios: [
        "Chiquimula",
        "Jocotán",
        "Esquipulas",
        "Camotán",
        "Concepción Las Minas",
        "San Juan Ermita",
        "Olopa",
        "Quezaltepeque",
        "San Jacinto",
        "San José La Arada",
      ],
    },
    {
      nombre: "Petén",
      municipios: [
        "Flores",
        "San José",
        "San Benito",
        "San Andrés",
        "La Libertad",
        "San Francisco",
        "Santa Ana",
        "Dolores",
        "San Luis",
        "Poptún",
        "Melchor de Mencos",
      ],
    },
    {
      nombre: "El Progreso",
      municipios: [
        "Guastatoya",
        "Morazán",
        "San Agustín Acasaguastlán",
        "San Cristóbal Acasaguastlán",
        "El Jícaro",
        "Sansare",
        "Sanarate",
        "San Antonio La Paz",
      ],
    },
    {
      nombre: "Quiché",
      municipios: [
        "Santa Cruz del Quiché",
        "Chichicastenango",
        "Patzité",
        "San Antonio Ilotenango",
        "San Pedro Jocopilas",
        "Cunén",
        "Sacapulas",
        "San Bartolomé Jocotenango",
        "San Juan Cotzal",
        "Joyabaj",
        "Nebaj",
        "Chajul",
        "Canillá",
        "Chicamán",
        "Uspantán",
        "Pachalum",
      ],
    },
    {
      nombre: "Escuintla",
      municipios: [
        "Escuintla",
        "Guanagazapa",
        "Iztapa",
        "La Democracia",
        "La Gomera",
        "Masagua",
        "Nueva Concepción",
        "Palín",
        "San José",
        "Siquinalá",
        "Tiquisate",
      ],
    },
    {
      nombre: "Guatemala",
      municipios: [
        "Guatemala",
        "Santa Catarina Pinula",
        "San José Pinula",
        "San José del Golfo",
        "Palencia",
        "Chinautla",
        "San Pedro Ayampuc",
        "Mixco",
        "San Pedro Sacatepéquez",
        "San Juan Sacatepéquez",
        "San Raymundo",
        "Chuarrancho",
        "Fraijanes",
        "Amatitlán",
        "Villa Nueva",
        "Villa Canales",
        "Petapa",
      ],
    },
    {
      nombre: "Huehuetenango",
      municipios: [
        "Huehuetenango",
        "Aguacatán",
        "Chiantla",
        "Colotenango",
        "Concepción",
        "Cuilco",
        "Jacaltenango",
        "La Democracia",
        "La Libertad",
        "Malacatancito",
        "Nentón",
        "San Pedro Necta",
        "San Juan Atitán",
        "San Gaspar Ixchil",
        "Santiago Chimaltenango",
        "Santa Ana Huista",
        "Santa Bárbara",
        "Santa Cruz Barillas",
        "San Rafael La Independencia",
        "San Miguel Acatán",
        "San Sebastián Huehuetenango",
        "Tectitán",
        "Todos Santos Cuchumatán",
        "San Juan Ixcoy",
        "Soloma",
        "Santa Eulalia",
        "San Mateo Ixtatán",
        "San Sebastián Coatán",
        "San Rafael Petzal",
        "Colotenango",
        "San Miguel Acatán",
        "Santa Cruz Barillas",
      ],
    },
    {
      nombre: "Izabal",
      municipios: [
        "Puerto Barrios",
        "Livingston",
        "El Estor",
        "Morales",
        "Los Amates",
      ],
    },
    {
      nombre: "Jalapa",
      municipios: [
        "Jalapa",
        "Mataquescuintla",
        "Monjas",
        "San Carlos Alzatate",
        "San Luis Jilotepeque",
        "San Manuel Chaparrón",
        "Santa María Xalapán",
      ],
    },
    {
      nombre: "Jutiapa",
      municipios: [
        "Jutiapa",
        "El Progreso",
        "Santa Catarina Mita",
        "Agua Blanca",
        "Asunción Mita",
        "Yupiltepeque",
        "Atescatempa",
        "Jerez",
        "El Adelanto",
        "Zapotitlán",
        "Comapa",
        "Jalpatagua",
        "Conguaco",
        "Moyuta",
        "Pasaco",
        "San José Acatempa",
        "Quesada",
      ],
    },
    {
      nombre: "Quetzaltenango",
      municipios: [
        "Quetzaltenango",
        "Salcajá",
        "Olintepeque",
        "San Carlos Sija",
        "Sibilia",
        "Cabricán",
        "Cajolá",
        "San Miguel Sigüilá",
        "Ostuncalco",
        "Concepción Chiquirichapa",
        "San Martín Sacatepéquez",
        "Almolonga",
        "Cantel",
        "Huitán",
        "Zunil",
        "Colomba",
        "San Francisco La Unión",
        "El Palmar",
        "Coatepeque",
        "Génova",
        "Flores Costa Cuca",
        "La Esperanza",
        "Palestina de los Altos",
      ],
    },
    {
      nombre: "Retalhuleu",
      municipios: [
        "Retalhuleu",
        "San Sebastián",
        "Santa Cruz Muluá",
        "San Martín Zapotitlán",
        "San Felipe",
        "San Andrés Villa Seca",
        "Champerico",
        "Nuevo San Carlos",
        "El Asintal",
      ],
    },
    {
      nombre: "Sacatepéquez",
      municipios: [
        "Antigua Guatemala",
        "Jocotenango",
        "Pastores",
        "Sumpango",
        "Santo Domingo Xenacoj",
        "Santiago Sacatepéquez",
        "San Bartolomé Milpas Altas",
        "San Lucas Sacatepéquez",
        "Santa Lucía Milpas Altas",
        "Magdalena Milpas Altas",
        "Santa María de Jesús",
        "Ciudad Vieja",
        "San Miguel Dueñas",
        "Alotenango",
        "San Antonio Aguas Calientes",
        "Santa Catarina Barahona",
      ],
    },
    {
      nombre: "San Marcos",
      municipios: [
        "San Marcos",
        "San Pedro Sacatepéquez",
        "San Antonio Sacatepéquez",
        "Comitancillo",
        "Concepción Tutuapa",
        "Tacaná",
        "Sibinal",
        "Tajumulco",
        "Tejutla",
        "San Rafael Pie de la Cuesta",
        "Nuevo Progreso",
        "El Tumbador",
        "El Rodeo",
        "Malacatán",
        "Catarina",
        "Ayutla (Tecún Umán)",
        "Ocos",
        "San Pablo",
        "El Quetzal",
        "La Reforma",
        "Pajapita",
        "Ixchiguán",
        "San José Ojetenam",
        "San Cristóbal Cucho",
        "Sipacapa",
        "Esquipulas Palo Gordo",
        "Río Blanco",
        "San Lorenzo",
      ],
    },
    {
      nombre: "Santa Rosa",
      municipios: [
        "Cuilapa",
        "Barberena",
        "Santa Rosa de Lima",
        "Casillas",
        "San Rafael Las Flores",
        "Oratorio",
        "San Juan Tecuaco",
        "Chiquimulilla",
        "Taxisco",
        "Santa María Ixhuatán",
        "Guazacapán",
        "Santa Cruz Naranjo",
        "Pueblo Nuevo Viñas",
        "Nueva Santa Rosa",
      ],
    },
    {
      nombre: "Sololá",
      municipios: [
        "Sololá",
        "San José Chacayá",
        "Santa María Visitación",
        "Santa Lucía Utatlán",
        "Nahualá",
        "Santa Catarina Ixtahuacán",
        "Santa Clara La Laguna",
        "Concepción",
        "San Andrés Semetabaj",
        "Panajachel",
        "Santa Catarina Palopó",
        "San Antonio Palopó",
        "San Lucas Tolimán",
        "Santa Cruz La Laguna",
        "San Pablo La Laguna",
        "San Marcos La Laguna",
        "San Juan La Laguna",
        "San Pedro La Laguna",
        "Santiago Atitlán",
      ],
    },
    {
      nombre: "Suchitepéquez",
      municipios: [
        "Mazatenango",
        "Cuyotenango",
        "San Francisco Zapotitlán",
        "San Bernardino",
        "San José El Ídolo",
        "Santo Domingo Suchitepéquez",
        "San Lorenzo",
        "Samayac",
        "San Pablo Jocopilas",
        "San Antonio Suchitepéquez",
        "San Miguel Panán",
        "San Gabriel",
        "Chicacao",
        "Patulul",
        "Santa Bárbara",
        "San Juan Bautista",
        "Santo Tomás La Unión",
        "Zunilito",
        "Pueblo Nuevo",
        "Río Bravo",
      ],
    },
    {
      nombre: "Totonicapán",
      municipios: [
        "Totonicapán",
        "San Cristóbal Totonicapán",
        "San Francisco El Alto",
        "San Andrés Xecul",
        "Momostenango",
        "Santa María Chiquimula",
        "Santa Lucía La Reforma",
        "San Bartolo Aguas Calientes",
      ],
    },
    {
      nombre: "Zacapa",
      municipios: [
        "Zacapa",
        "Estanzuela",
        "Río Hondo",
        "Gualán",
        "Teculután",
        "Usumatlán",
        "Cabañas",
        "San Diego",
        "La Unión",
        "Huité",
      ],
    },
  ];