import localFont from "next/font/local";
import "./globals.css";
import Header from "@components/Header";

const poppins = localFont({
  src: [
    {
      path: "./fonts/Poppins/Poppins-Light.ttf",
      weight: "400",
    },
  ],
  variable: "--font-poppins",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} font-sans`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
